(() => {
'use strict';
const VERSION='4.5';
const FLIGHTS_KEY='pilotlog_flights_v1', ROSTER_KEY='pilotlog_roster_v2', DUTY_KEY='pilotlog_duties_v2', TRIPS_KEY='pilotlog_trips_v1', PAY_SETTINGS_KEY='pilotlog_pay_settings_v1', PAY_MONTH_KEY='pilotlog_pay_month_v1', FX_KEY='pilotlog_fx_v1';
const $=id=>document.getElementById(id), load=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}}, save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const makeId=()=>`id-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;
const mins=t=>{if(!t)return null;const [h,m]=String(t).split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:null};
const diff=(a,b)=>{if(a==null||b==null)return 0;let d=b-a;if(d<0)d+=1440;return d};
const fmt=m=>`${Math.floor(Math.max(0,Number(m)||0)/60)}:${String(Math.round(Math.max(0,Number(m)||0))%60).padStart(2,'0')}`;
const credit=m=>m>0?Math.ceil(m/30)*30:0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const csv=s=>`"${String(s??'').replace(/"/g,'""')}"`;
const dateOnly=d=>new Date(`${d}T00:00:00`);
const sum=(a,f)=>a.reduce((x,y)=>x+(Number(f(y))||0),0);

function calcEntry(){const block=diff(mins($('out').value),mins($('in').value)), flight=diff(mins($('off').value),mins($('on').value)), cr=credit(block);$('blockDisplay').value=fmt(block);$('creditDisplay').value=fmt(cr);$('calcPreview').textContent=`Block ${fmt(block)} • Flight ${fmt(flight)} • Credit ${fmt(cr)}`;return{block,flight,credit:cr}}
function show(id){document.querySelectorAll('main>section').forEach(s=>s.classList.toggle('hidden',s.id!==id));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='totalsView')renderTotals();if(id==='tripsView')renderTrips();if(id==='payrollView')renderPayroll();scrollTo(0,0)}
function resetEntry(){const f=$('flightForm');f.reset();$('editId').value='';$('date').value=today();$('dutyTypeFlight').value='Flight';$('role').value='PIC';$('landings').value=1;$('night').value='00:00';$('ifr').value='yes';$('entryTitle').textContent='Add log entry';$('saveEntryBtn').textContent='Save entry';calcEntry()}
function entrySig(f){return [f.date,f.dutyType,f.flightNo,f.dep,f.arr,f.schedOut,f.schedIn].map(x=>String(x||'').toUpperCase()).join('|')}
function dutySig(d){return [d.date,d.type,d.report,d.end,d.notes].map(x=>String(x||'').toUpperCase()).join('|')}
function startOfDays(n){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-n+1);return d}
function rolling(fs,n,field='block'){const c=startOfDays(n);return sum(fs,f=>dateOnly(f.date)>=c?f[field]:0)}
function isFlight(f){return (f.dutyType||'Flight')==='Flight'}
function isSim(f){return (f.dutyType||'')==='Simulator'||f.sim==='yes'}
function picMins(f){return f.role==='PIC'||f.role==='Instructor'||f.role==='Examiner'?Number(f.block)||0:0}
function instrMins(f){return f.instructionType||f.role==='Instructor'||f.role==='Examiner' ? (Number(f.block)||Number(f.flight)||0) : 0}

function flightHtml(fs,full=false){if(!fs.length)return'<div class="empty">No entries yet.</div>';return fs.map(f=>`<div class="flight"><div><div class="route">${esc(f.dep||f.dutyType||'Entry')}${f.arr?` → ${esc(f.arr)}`:''}</div><div class="small">${esc(f.date)} ${esc(f.flightNo||'')}</div><span class="pill">${esc(f.dutyType||'Flight')}</span>${f.type?`<span class="pill">${esc(f.type)}</span>`:''}${f.instructionType?`<span class="pill green">${esc(f.instructionType)}</span>`:''}</div><div class="meta"><b>${fmt(f.block)}</b> block<br><span class="small">${fmt(f.credit??credit(Number(f.block)||0))} credit</span>${full?`<div class="list-actions"><button class="secondary" data-edit-flight="${f.id}">Edit</button><button class="danger" data-delete-flight="${f.id}">Delete</button></div>`:''}</div></div>`).join('')}
function render(){const fs=load(FLIGHTS_KEY).sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('mBlock').textContent=fmt(sum(fs,f=>isFlight(f)?f.block:0));$('mCredit').textContent=fmt(sum(fs,f=>f.credit??credit(Number(f.block)||0)));$('mPic').textContent=fmt(sum(fs,picMins));$('mTri').textContent=fmt(sum(fs,instrMins));$('p28').textContent=fmt(rolling(fs.filter(isFlight),28));$('p90').textContent=fmt(rolling(fs.filter(isFlight),90));$('p365').textContent=fmt(rolling(fs.filter(isFlight),365));$('recentFlights').innerHTML=flightHtml(fs.slice(0,6));$('allFlights').innerHTML=flightHtml(fs,true);renderRoster();renderDuty()}
function renderRoster(){const rs=load(ROSTER_KEY).sort((a,b)=>`${a.date}${a.std||''}`.localeCompare(`${b.date}${b.std||''}`));const now=today();const up=rs.filter(r=>r.date>=now&&r.status!=='done').slice(0,6);$('upcomingRoster').innerHTML=up.length?up.map(r=>`<div class="rowitem"><div><b>${esc(r.flightNo||r.type||'Roster')}</b><div class="small">${esc(r.date)} ${esc(r.dep||'')} ${r.arr?'→ '+esc(r.arr):''}</div></div><div class="meta">${esc(r.std||'')} ${r.sta?'– '+esc(r.sta):''}</div></div>`).join(''):'<div class="empty">No upcoming roster.</div>';$('rosterList').innerHTML=rs.length?rs.map(r=>`<div class="rowitem"><div><b>${esc(r.flightNo||r.type||'Roster')}</b><div class="small">${esc(r.date)} ${esc(r.dep||'')} ${r.arr?'→ '+esc(r.arr):''}</div></div><div class="meta">${esc(r.std||'')} ${r.sta?'– '+esc(r.sta):''}<div class="list-actions"><button class="secondary" data-roster-action="${r.id}">${r.status==='done'?'Undo':'Open'}</button></div></div></div>`).join(''):'<div class="empty">No roster imported.</div>'}
function renderDuty(){const ds=load(DUTY_KEY).sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('dutyList').innerHTML=ds.length?ds.map(d=>`<div class="rowitem"><div><b>${esc(d.type)}</b><div class="small">${esc(d.date)} • ${esc(d.notes||'')}</div></div><div class="meta"><b>${fmt(d.minutes)}</b><br>${esc(d.report||'')}–${esc(d.end||'')}<div class="list-actions"><button class="danger" data-delete-duty="${d.id}">Delete</button></div></div></div>`).join(''):'<div class="empty">No duties yet.</div>'}

function renderTotals(){const fs=load(FLIGHTS_KEY), ds=load(DUTY_KEY);const flying=fs.filter(isFlight);$('tBlock').textContent=fmt(sum(flying,f=>f.block));$('tCredit').textContent=fmt(sum(fs,f=>f.credit??credit(Number(f.block)||0)));$('tSim').textContent=fmt(sum(fs,f=>isSim(f)?(f.block||f.flight||diff(mins(f.schedOut),mins(f.schedIn))):0));$('tDuty').textContent=fmt(sum(ds,d=>d.minutes));$('tPic').textContent=fmt(sum(fs,picMins));$('tInstruction').textContent=fmt(sum(fs,instrMins));const now=new Date(), y=now.getFullYear(), m=now.getMonth();const month=sum(flying,f=>{const d=dateOnly(f.date);return d.getFullYear()===y&&d.getMonth()===m?f.block:0}), year=sum(flying,f=>dateOnly(f.date).getFullYear()===y?f.block:0);$('periodTotals').innerHTML=[['This Month',month],['This Year',year],['Last 28 days',rolling(flying,28)],['Last 90 days',rolling(flying,90)],['Last 365 days',rolling(flying,365)]].map(([n,v])=>`<div class="stat-row"><span>${n}</span><b>${fmt(v)}</b></div>`).join('');const ac={};fs.forEach(f=>{const t=(f.type||'Unspecified').toUpperCase();if(!ac[t])ac[t]={f:0,s:0};if(isSim(f))ac[t].s+=Number(f.block||f.flight||diff(mins(f.schedOut),mins(f.schedIn)))||0;else if(isFlight(f))ac[t].f+=Number(f.block)||0});$('aircraftBreakdown').innerHTML=Object.keys(ac).length?Object.entries(ac).sort().map(([t,v])=>`<div class="stat-row"><span><b>${esc(t)}</b><div class="small">Flying ${fmt(v.f)} • Simulator ${fmt(v.s)}</div></span><b>${fmt(v.f+v.s)}</b></div>`).join(''):'<div class="empty">No aircraft data.</div>';const by={};ds.forEach(d=>by[d.type||'Duty']=(by[d.type||'Duty']||0)+(Number(d.minutes)||0));$('dutyBreakdown').innerHTML=Object.keys(by).length?Object.entries(by).sort().map(([n,v])=>`<div class="stat-row"><span>${esc(n)}</span><b>${fmt(v)}</b></div>`).join(''):'<div class="empty">No duty data.</div>'}

function dtFrom(date,time){if(!date||!time)return null;const [h,m]=time.split(':').map(Number);const d=new Date(`${date}T00:00:00`);d.setHours(h,m,0,0);return d}
function dutyInterval(d){const s=dtFrom(d.date,d.report),e=dtFrom(d.date,d.end);if(!s||!e)return null;if(e<s)e.setDate(e.getDate()+1);return[s,e]}
function entryInterval(f){const t=f.out||f.schedOut, u=f.in||f.schedIn;if(!f.date||!t||!u)return null;const s=dtFrom(f.date,t),e=dtFrom(f.date,u);if(e<s)e.setDate(e.getDate()+1);return[s,e]}
function overlapMins(a,b,s,e){const x=Math.max(a.getTime(),s.getTime()),y=Math.min(b.getTime(),e.getTime());return Math.max(0,Math.round((y-x)/60000))}
function tripCalc(){const s=new Date($('tripStart').value),e=new Date($('tripEnd').value);if(!Number.isFinite(s.getTime())||!Number.isFinite(e.getTime())||e<=s){$('tripTime').value=$('tripDuty').value=$('tripLayover').value=$('tripBlock').value='0:00';return null}const trip=Math.round((e-s)/60000);const duties=load(DUTY_KEY);let duty=0;duties.forEach(d=>{const iv=dutyInterval(d);if(iv)duty+=overlapMins(iv[0],iv[1],s,e)});const fs=load(FLIGHTS_KEY);let block=0;fs.filter(isFlight).forEach(f=>{const iv=entryInterval(f);if(iv&&overlapMins(iv[0],iv[1],s,e)>0)block+=Number(f.block)||0});const lay=Math.max(0,trip-duty);$('tripTime').value=fmt(trip);$('tripDuty').value=fmt(duty);$('tripLayover').value=fmt(lay);$('tripBlock').value=fmt(block);return{trip,duty,layover:lay,block}}
function resetTrip(){ $('tripForm').reset();$('tripEditId').value='';['tripTime','tripDuty','tripLayover','tripBlock'].forEach(id=>$(id).value='0:00') }
function renderTrips(){const ts=load(TRIPS_KEY).sort((a,b)=>String(b.start).localeCompare(String(a.start)));$('tripList').innerHTML=ts.length?ts.map(t=>`<div class="rowitem"><div><b>${esc(t.base||'Trip')} ${t.stations?'• '+esc(t.stations):''}</b><div class="small">${esc(String(t.start).replace('T',' '))} → ${esc(String(t.end).replace('T',' '))}</div><div class="small">Duty ${fmt(t.duty)} • Block ${fmt(t.block)}</div></div><div class="meta"><b>${fmt(t.layover)}</b><br><span class="small">paid layover</span><div class="list-actions"><button class="danger" data-delete-trip="${t.id}">Delete</button></div></div></div>`).join(''):'<div class="empty">No trips yet.</div>'}

function unfoldIcs(text){return text.replace(/\r?\n[ \t]/g,'')}
function icsVal(line){const i=line.indexOf(':');return i<0?'':line.slice(i+1).replace(/\\n/g,'\n').replace(/\\,/g,',').replace(/\\;/g,';')}
function parseIcsDate(v){v=String(v||'').trim();const m=v.match(/^(\d{4})(\d{2})(\d{2})(?:T(\d{2})(\d{2})(\d{2})?Z?)?/);if(!m)return null;return{date:`${m[1]}-${m[2]}-${m[3]}`,time:m[4]?`${m[4]}:${m[5]}`:''}}
function parseIcs(text){const blocks=unfoldIcs(text).split('BEGIN:VEVENT').slice(1).map(x=>x.split('END:VEVENT')[0]);return blocks.map(b=>{const o={};b.split(/\r?\n/).forEach(line=>{const k=line.split(':')[0].split(';')[0];if(['SUMMARY','DESCRIPTION','DTSTART','DTEND','UID'].includes(k))o[k]=icsVal(line)});o._start=parseIcsDate(o.DTSTART);o._end=parseIcsDate(o.DTEND);return o}).filter(e=>e._start)}
function classify(summary){const s=String(summary||'').toUpperCase().trim();const fl=s.match(/\b([A-Z0-9]{2,3}\s?\d{2,4})\b.*?\b([A-Z]{3})\b\s*(?:→|->|–|-)\s*\b([A-Z]{3})\b/);if(fl)return{kind:'flight',flightNo:fl[1].replace(/\s+/g,''),dep:fl[2],arr:fl[3]};const ac=(s.match(/\bA(319|320|321)\b/)||[])[0]||'';if(/\bRT[ -]?A3(19|20|21)\b|RECURRENT TRAINING|\bSIM(?:ULATOR)?\b|\bOPC\b|\bLPC\b/.test(s))return{kind:'entry',dutyType:'Simulator',aircraftType:ac};if(/\bSTBY\b|STANDBY/.test(s))return{kind:'entry',dutyType:'STBY',aircraftType:ac};if(/\bDHD\b|DEADHEAD/.test(s))return{kind:'entry',dutyType:'DHD',aircraftType:ac};if(/GROUND|COURSE|TRAINING/.test(s))return{kind:'entry',dutyType:'Ground Course',aircraftType:ac};if(/^DUTY\b|\bDUTY\s*[•:-]/.test(s))return{kind:'duty',dutyType:'Flight Duty'};if(/^OFF\b/.test(s))return{kind:'ignore'};return{kind:'unknown'}}
function zuluTimes(desc){const d=String(desc||'');const out=(d.match(/Scheduled (?:take-off\/)?departure\s+(\d{1,2}:\d{2})Z/i)||[])[1]||'';const inn=(d.match(/Scheduled arrival\s+(\d{1,2}:\d{2})Z/i)||[])[1]||'';const report=(d.match(/Reporting\s+(\d{1,2}:\d{2})Z/i)||[])[1]||'';const end=(d.match(/Release\s+(\d{1,2}:\d{2})Z/i)||[])[1]||'';return{out,inn,report,end}}
function importCalendar(events){let fs=load(FLIGHTS_KEY),rs=load(ROSTER_KEY),ds=load(DUTY_KEY),seenF=new Set(fs.map(entrySig)),seenR=new Set(rs.map(r=>[r.date,r.flightNo,r.dep,r.arr,r.std,r.sta].map(x=>String(x||'').toUpperCase()).join('|'))),seenD=new Set(ds.map(dutySig));let sectors=0,duties=0,other=0,skipped=0;events.forEach(ev=>{const c=classify(ev.SUMMARY),z=zuluTimes(ev.DESCRIPTION),date=ev._start.date;if(c.kind==='ignore'||c.kind==='unknown'){skipped++;return}if(c.kind==='flight'){const std=z.out||ev._start.time||'',sta=z.inn||(ev._end?ev._end.time:'');const r={id:makeId(),date,flightNo:c.flightNo,dep:c.dep,arr:c.arr,std,sta,report:'',endDuty:'',type:'',reg:'',status:'planned',source:'calendar'};const sr=[r.date,r.flightNo,r.dep,r.arr,r.std,r.sta].map(x=>String(x||'').toUpperCase()).join('|');if(!seenR.has(sr)){rs.push(r);seenR.add(sr)}const f={id:makeId(),dutyType:'Flight',date,flightNo:c.flightNo,dep:c.dep,arr:c.arr,type:'',reg:'',schedOut:std,schedIn:sta,out:'',off:'',on:'',in:'',block:0,flight:0,credit:0,role:'PIC',instructionType:'',landings:1,night:'00:00',sim:'no',ifr:'yes',remarks:'Imported from calendar',source:'calendar'};const sf=entrySig(f);if(!seenF.has(sf)){fs.push(f);seenF.add(sf);sectors++}else skipped++;return}if(c.kind==='duty'){const rep=z.report||ev._start.time||'',end=z.end||(ev._end?ev._end.time:'');const d={id:makeId(),date,type:c.dutyType,report:rep,end,minutes:diff(mins(rep),mins(end)),notes:ev.SUMMARY||'',source:'calendar'};const sd=dutySig(d);if(!seenD.has(sd)){ds.push(d);seenD.add(sd);duties++}else skipped++;return}if(c.kind==='entry'){const so=ev._start.time||'',si=ev._end?ev._end.time:'';const f={id:makeId(),dutyType:c.dutyType,date,flightNo:'',dep:'',arr:'',type:c.aircraftType||'',reg:'',schedOut:so,schedIn:si,out:'',off:'',on:'',in:'',block:c.dutyType==='Simulator'?diff(mins(so),mins(si)):0,flight:0,credit:0,role:'PIC',instructionType:'',landings:0,night:'00:00',sim:c.dutyType==='Simulator'?'yes':'no',ifr:'no',remarks:`Imported from calendar: ${ev.SUMMARY||''}`,source:'calendar'};const sf=entrySig(f);if(!seenF.has(sf)){fs.push(f);seenF.add(sf);other++}else skipped++}});save(FLIGHTS_KEY,fs);save(ROSTER_KEY,rs);save(DUTY_KEY,ds);return{sectors,duties,other,skipped}}

function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());cell='';if(row.some(x=>x!==''))rows.push(row);row=[]}else cell+=c}row.push(cell.trim());if(row.some(x=>x!==''))rows.push(row);return rows}
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,''), aliases={date:['date','day'],flightNo:['flightno','flightnumber','flight','flt'],dep:['dep','departure','from','origin'],arr:['arr','arrival','to','destination'],report:['report','reporting','reporttime'],std:['std','departuretime','scheduleddeparture','offblock'],sta:['sta','arrivaltime','scheduledarrival','onblock'],endDuty:['endduty','dutyend','end','released'],type:['type','aircrafttype','acfttype'],reg:['reg','registration','aircraftregistration']};
const fieldFor=h=>{const x=norm(h);return Object.keys(aliases).find(k=>aliases[k].includes(x))||null};
function normalDate(v){v=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const m=v.match(/^(\d{1,2})[\/.\-](\d{1,2})[\/.\-](\d{2,4})$/);if(m){const y=m[3].length===2?'20'+m[3]:m[3];return`${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}return v}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function logTenExport(){const fs=load(FLIGHTS_KEY).filter(f=>isFlight(f)||isSim(f)||f.dutyType==='Ground Course');if(!fs.length)return alert('No entries to export');const headers=['flight_flightDate','flight_type','flight_flightNumber','flight_from','flight_to','flight_scheduledDepartureTime','flight_actualDepartureTime','flight_scheduledArrivalTime','flight_actualArrivalTime','flight_totalTime','flight_pic','flight_sic','flight_dualGiven','flight_simulator','flight_ground','flight_remarks','aircraft_aircraftID','aircraftType_type'];const rows=fs.map(f=>{const total=isFlight(f)?fmt(f.block):'';const sim=isSim(f)?fmt(f.block||diff(mins(f.schedOut),mins(f.schedIn))):'';const ground=f.dutyType==='Ground Course'?fmt(diff(mins(f.schedOut),mins(f.schedIn))):'';return [f.date,'',f.flightNo||'',f.dep||'',f.arr||'',f.schedOut||'',f.out||'',f.schedIn||'',f.in||'',total,(f.role==='PIC'||f.role==='Instructor'||f.role==='Examiner')?total:'',f.role==='SIC'?total:'',f.instructionType?total:'',sim,ground,f.remarks||'',f.reg||'',f.type||'']});download(`PilotLog_LogTen_${today()}.txt`,[headers.join('\t'),...rows.map(r=>r.map(v=>String(v??'').replace(/[\t\r\n]+/g,' ')).join('\t'))].join('\n'),'text/tab-separated-values')}


const PAY_DEFAULTS={joinDate:'2014-04-01',base:46500,allowance:8000,transport:2500,pos:4000,telephone:500,uniform:300,meal:520,deduction:-3000,seniority2:10,seniority12:15,t1Max:25,t1Rate:170,t2Max:50,t2Rate:370,t3Max:75,t3Rate:665,t4Rate:1400,trainingRate:500,layoverRate:25,simAllowance:1000,simCredit:5,groundCredit:5,dayOffRate:1000};
function loadObject(k,def={}){try{const v=JSON.parse(localStorage.getItem(k)||'null');return v&&typeof v==='object'&&!Array.isArray(v)?v:def}catch{return def}}
function paySettings(){return {...PAY_DEFAULTS,...loadObject(PAY_SETTINGS_KEY,{})}}
function monthNow(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function inMonth(date,month){return String(date||'').slice(0,7)===month}
function money(v){return new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v)||0)}
function trainingSector(f){return isFlight(f)&&Boolean(f.instructionType||f.role==='Instructor'||f.role==='Examiner')}
function payrollCreditMins(f,st){if(isFlight(f))return Number(f.credit??credit(Number(f.block)||0))||0;if(isSim(f))return Math.round(Number(st.simCredit||0)*60);if(f.dutyType==='Ground Course')return Math.round(Number(st.groundCredit||0)*60);return 0}
function tierPay(hours,st){hours=Math.max(0,Number(hours)||0);const a=Math.max(0,Number(st.t1Max)||0),b=Math.max(a,Number(st.t2Max)||a),c=Math.max(b,Number(st.t3Max)||b);let left=hours,total=0;const h1=Math.min(left,a);total+=h1*Number(st.t1Rate||0);left-=h1;const h2=Math.min(Math.max(0,left),b-a);total+=h2*Number(st.t2Rate||0);left-=h2;const h3=Math.min(Math.max(0,left),c-b);total+=h3*Number(st.t3Rate||0);left-=h3;if(left>0)total+=left*Number(st.t4Rate||0);return total}
function seniorityPct(st,month){if(!st.joinDate)return 0;const start=new Date(`${st.joinDate}T00:00:00`),[y,m]=month.split('-').map(Number),end=new Date(y,m,0,23,59,59);if(!Number.isFinite(start.getTime()))return 0;const years=(end-start)/(365.2425*86400000);if(years>12)return Number(st.seniority12||0);if(years>2)return Number(st.seniority2||0);return 0}
function monthExtras(month){const all=loadObject(PAY_MONTH_KEY,{});return {...(all[month]||{dayOffCount:0,arrears:0})}}
function saveMonthExtras(month,x){const all=loadObject(PAY_MONTH_KEY,{});all[month]=x;localStorage.setItem(PAY_MONTH_KEY,JSON.stringify(all))}
function payrollData(month){const st=paySettings(),fs=load(FLIGHTS_KEY).filter(f=>inMonth(f.date,month)),trips=load(TRIPS_KEY).filter(t=>String(t.start||'').slice(0,7)===month),extras=monthExtras(month);const creditMins=sum(fs,f=>payrollCreditMins(f,st));const creditHours=creditMins/60;const training=fs.filter(trainingSector).length;const sims=fs.filter(isSim).length;const grounds=fs.filter(f=>f.dutyType==='Ground Course').length;const layMins=sum(trips,t=>t.layover);const layHours=layMins/60;const seniorPct=seniorityPct(st,month),seniority=Number(st.base||0)*seniorPct/100;const fixed=Number(st.base||0)+Number(st.allowance||0)+Number(st.transport||0)+seniority+Number(st.pos||0)+Number(st.telephone||0)+Number(st.uniform||0)+Number(st.meal||0)+Number(st.deduction||0);const flightPay=tierPay(creditHours,st),trainingPay=training*Number(st.trainingRate||0),layoverPay=layHours*Number(st.layoverRate||0),simPay=sims*Number(st.simAllowance||0),dayOffPay=Number(extras.dayOffCount||0)*Number(st.dayOffRate||0),arrears=Number(extras.arrears||0);const total=fixed+flightPay+trainingPay+layoverPay+simPay+dayOffPay+arrears;return{st,extras,creditMins,creditHours,training,sims,grounds,layMins,layHours,seniorPct,seniority,fixed,flightPay,trainingPay,layoverPay,simPay,dayOffPay,arrears,total}}
function fxStore(){return loadObject(FX_KEY,{})}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
async function fetchFxForDate(dateStr){for(let back=0;back<8;back++){const d=new Date(`${dateStr}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-back);const key=dateKey(new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));try{const r=await fetch(`https://${key}.currency-api.pages.dev/v1/currencies/eur.json`,{cache:'no-store'});if(!r.ok)continue;const j=await r.json();const rate=Number(j&&j.eur&&j.eur.mad);if(rate>0)return{rate,date:j.date||key}}catch(e){}}throw new Error('FX unavailable')}
async function fetchLatestFx(){const r=await fetch('https://latest.currency-api.pages.dev/v1/currencies/eur.json',{cache:'no-store'});if(!r.ok)throw new Error('FX unavailable');const j=await r.json(),rate=Number(j&&j.eur&&j.eur.mad);if(!(rate>0))throw new Error('MAD rate unavailable');return{rate,date:j.date||today()}}
async function getMonthFx(month){const store=fxStore();if(store[month]&&store[month].locked)return store[month];const [y,m]=month.split('-').map(Number),target=`${y}-${String(m).padStart(2,'0')}-30`,now=new Date(),targetDate=new Date(`${target}T23:59:59`),monthStart=new Date(y,m-1,1),nextMonth=new Date(y,m,1);if(monthStart>now)return{rate:null,locked:false,status:'future'};if(now>=targetDate||now>=nextMonth){const got=await fetchFxForDate(target),locked={...got,locked:true};store[month]=locked;localStorage.setItem(FX_KEY,JSON.stringify(store));return locked}const live=await fetchLatestFx();return{...live,locked:false,status:'live'}}
function fillPaySettings(){const st=paySettings(),map={setJoinDate:'joinDate',setBase:'base',setAllowance:'allowance',setTransport:'transport',setPos:'pos',setTelephone:'telephone',setUniform:'uniform',setMeal:'meal',setDeduction:'deduction',setSeniority2:'seniority2',setSeniority12:'seniority12',setT1Max:'t1Max',setT1Rate:'t1Rate',setT2Max:'t2Max',setT2Rate:'t2Rate',setT3Max:'t3Max',setT3Rate:'t3Rate',setT4Rate:'t4Rate',setTrainingRate:'trainingRate',setLayoverRate:'layoverRate',setSimAllowance:'simAllowance',setSimCredit:'simCredit',setGroundCredit:'groundCredit',setDayOffRate:'dayOffRate'};Object.entries(map).forEach(([id,k])=>{if($(id))$(id).value=st[k]})}
function readPaySettings(){const map={setJoinDate:'joinDate',setBase:'base',setAllowance:'allowance',setTransport:'transport',setPos:'pos',setTelephone:'telephone',setUniform:'uniform',setMeal:'meal',setDeduction:'deduction',setSeniority2:'seniority2',setSeniority12:'seniority12',setT1Max:'t1Max',setT1Rate:'t1Rate',setT2Max:'t2Max',setT2Rate:'t2Rate',setT3Max:'t3Max',setT3Rate:'t3Rate',setT4Rate:'t4Rate',setTrainingRate:'trainingRate',setLayoverRate:'layoverRate',setSimAllowance:'simAllowance',setSimCredit:'simCredit',setGroundCredit:'groundCredit',setDayOffRate:'dayOffRate'};const st={};Object.entries(map).forEach(([id,k])=>st[k]=k==='joinDate'?$(id).value:Number($(id).value||0));return st}
let payrollRenderToken=0;
async function renderPayroll(){const token=++payrollRenderToken,month=$('payrollMonth').value||monthNow();if(!$('payrollMonth').value)$('payrollMonth').value=month;const ex=monthExtras(month);$('payDayOffCount').value=ex.dayOffCount||0;$('payArrears').value=ex.arrears||0;const p=payrollData(month);$('payCredits').textContent=fmt(p.creditMins);$('payLayover').textContent=fmt(p.layMins);$('payTrainingSectors').textContent=p.training;$('paySimCount').textContent=p.sims;$('payTotalDhm').textContent=`${money(p.total)} DHM`;$('payTotalEur').textContent='…';$('payBreakdown').innerHTML=[['Fixed salary',p.fixed],['Seniority ('+money(p.seniorPct)+'%)',p.seniority],['Credit hours pay',p.flightPay],['Training sectors ('+p.training+')',p.trainingPay],['Layover ('+p.layHours.toFixed(2)+' h)',p.layoverPay],['Simulator allowance ('+p.sims+')',p.simPay],['Day OFF premium ('+(p.extras.dayOffCount||0)+')',p.dayOffPay],['Arrears / adjustments',p.arrears]].map(([n,v])=>`<div class="stat-row"><span>${esc(n)}</span><b class="money">${money(v)} DHM</b></div>`).join('');$('payFxStatus').textContent='Loading EUR/MAD…';try{const fx=await getMonthFx(month);if(token!==payrollRenderToken)return;if(!fx.rate){$('payTotalEur').textContent='—';$('payFxStatus').textContent='FX not available for a future month.';return}$('payTotalEur').textContent=`≈ €${money(p.total/fx.rate)}`;$('payFxStatus').innerHTML=`EUR/MAD ${money(fx.rate)} • ${esc(fx.date)} ${fx.locked?'<span class="fx-lock">LOCKED</span>':'<span class="fx-live">LIVE • locks on day 30</span>'}`}catch(e){if(token!==payrollRenderToken)return;$('payTotalEur').textContent='—';$('payFxStatus').textContent='FX unavailable. Payroll in DHM is unaffected.'}}

async function clearOldCaches(){try{if('serviceWorker'in navigator){for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister()}if('caches'in window){for(const k of await caches.keys())if(k.startsWith('pilotlog-'))await caches.delete(k)}}catch(e){console.warn(e)}}

document.addEventListener('DOMContentLoaded',()=>{
clearOldCaches();
document.querySelector('.nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b){e.preventDefault();show(b.dataset.view)}});
['out','off','on','in'].forEach(id=>$(id).addEventListener('input',calcEntry));
$('flightForm').addEventListener('submit',e=>{e.preventDefault();const c=calcEntry(),dutyType=$('dutyTypeFlight').value;if(!$('date').value)return alert('Please enter the date.');if((dutyType==='Flight'||dutyType==='DHD')&&(!$('dep').value.trim()||!$('arr').value.trim()))return alert('Please enter From and To.');const id=$('editId').value||makeId();const f={id,dutyType,date:$('date').value,flightNo:$('flightNo').value.trim().toUpperCase(),reg:$('reg').value.trim().toUpperCase(),type:$('type').value.trim().toUpperCase(),dep:$('dep').value.trim().toUpperCase(),arr:$('arr').value.trim().toUpperCase(),schedOut:$('schedOut').value,schedIn:$('schedIn').value,out:$('out').value,off:$('off').value,on:$('on').value,in:$('in').value,block:c.block,flight:c.flight,credit:c.credit,role:$('role').value,instructionType:$('instructionType').value,landings:Number($('landings').value||0),night:$('night').value,sim:dutyType==='Simulator'?'yes':'no',ifr:$('ifr').value,remarks:$('remarks').value.trim()};let fs=load(FLIGHTS_KEY);const i=fs.findIndex(x=>x.id===id);if(i>=0)fs[i]={...fs[i],...f};else fs.push(f);save(FLIGHTS_KEY,fs);resetEntry();render();show('dashboardView');alert(i>=0?'Entry updated.':'Entry saved.')});
$('clearForm').addEventListener('click',resetEntry);
$('dutyForm').addEventListener('submit',e=>{e.preventDefault();const ds=load(DUTY_KEY),rep=$('reportTime').value,end=$('endDuty').value;ds.push({id:makeId(),date:$('dutyDate').value,type:$('dutyType').value,report:rep,end,minutes:diff(mins(rep),mins(end)),notes:$('dutyNotes').value.trim()});save(DUTY_KEY,ds);e.target.reset();$('dutyDate').value=today();render()});
$('tripStart').addEventListener('input',tripCalc);$('tripEnd').addEventListener('input',tripCalc);$('calcTrip').addEventListener('click',tripCalc);$('clearTrip').addEventListener('click',resetTrip);
$('tripForm').addEventListener('submit',e=>{e.preventDefault();const c=tripCalc();if(!c)return alert('Enter a valid Trip Start and Trip End.');const ts=load(TRIPS_KEY),id=$('tripEditId').value||makeId(),t={id,base:$('tripBase').value.trim().toUpperCase(),stations:$('tripStations').value.trim().toUpperCase(),start:$('tripStart').value,end:$('tripEnd').value,trip:c.trip,duty:c.duty,layover:c.layover,block:c.block,remarks:$('tripRemarks').value.trim()};const i=ts.findIndex(x=>x.id===id);if(i>=0)ts[i]=t;else ts.push(t);save(TRIPS_KEY,ts);resetTrip();renderTrips();alert('Trip saved.')});
$('exportCsv').addEventListener('click',()=>{const d=load(FLIGHTS_KEY);if(!d.length)return alert('No entries to export');const cols=['dutyType','date','flightNo','reg','type','dep','arr','schedOut','schedIn','out','off','on','in','block','credit','flight','role','instructionType','landings','night','ifr','remarks'];download('pilotlog_logbook.csv',[cols.join(','),...d.map(r=>cols.map(c=>csv(r[c])).join(','))].join('\n'),'text/csv')});
$('exportLogTen').addEventListener('click',logTenExport);
$('deleteAll').addEventListener('click',()=>{if(confirm('Delete all saved entries?')){localStorage.removeItem(FLIGHTS_KEY);render()}});$('clearRoster').addEventListener('click',()=>{if(confirm('Clear imported roster?')){localStorage.removeItem(ROSTER_KEY);render()}});
$('exportRoster').addEventListener('click',()=>{const d=load(ROSTER_KEY);if(!d.length)return alert('No roster to export');const cols=['date','flightNo','dep','arr','report','std','sta','endDuty','type','reg','status'];download('pilotlog_roster.csv',[cols.join(','),...d.map(r=>cols.map(c=>csv(r[c])).join(','))].join('\n'),'text/csv')});
$('calendarFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const events=parseIcs(await file.text());if(!events.length)throw new Error('No calendar events found.');const r=importCalendar(events);e.target.value='';render();$('calendarImportStatus').textContent=`Imported ${r.sectors} flight sectors, ${r.duties} duties and ${r.other} other entries. ${r.skipped} duplicates/unsupported skipped.`;alert(`Imported: ${r.sectors} flights • ${r.duties} duties • ${r.other} other entries`)}catch(err){alert('Calendar import failed: '+err.message)}});
$('rosterFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const rows=parseCsv(await file.text());if(rows.length<2)return alert('CSV contains no data');const map=rows[0].map(fieldFor),imp=rows.slice(1).map(r=>{const o={id:makeId(),status:'planned'};map.forEach((k,i)=>{if(k)o[k]=r[i]||''});o.date=normalDate(o.date);['dep','arr','flightNo','type','reg'].forEach(k=>o[k]=(o[k]||'').toUpperCase());return o}).filter(x=>x.date&&(x.dep||x.arr||x.flightNo));save(ROSTER_KEY,[...load(ROSTER_KEY),...imp]);e.target.value='';render();alert(`${imp.length} roster sectors imported`)});

$('payrollMonth').addEventListener('change',renderPayroll);
$('recalcPayroll').addEventListener('click',()=>{const month=$('payrollMonth').value||monthNow();saveMonthExtras(month,{dayOffCount:Number($('payDayOffCount').value||0),arrears:Number($('payArrears').value||0)});renderPayroll()});
$('payDayOffCount').addEventListener('change',()=>{const month=$('payrollMonth').value||monthNow();saveMonthExtras(month,{dayOffCount:Number($('payDayOffCount').value||0),arrears:Number($('payArrears').value||0)});renderPayroll()});
$('payArrears').addEventListener('change',()=>{const month=$('payrollMonth').value||monthNow();saveMonthExtras(month,{dayOffCount:Number($('payDayOffCount').value||0),arrears:Number($('payArrears').value||0)});renderPayroll()});
$('paySettingsForm').addEventListener('submit',e=>{e.preventDefault();localStorage.setItem(PAY_SETTINGS_KEY,JSON.stringify(readPaySettings()));renderPayroll();alert('Payroll settings saved.')});
$('resetPaySettings').addEventListener('click',()=>{if(confirm('Restore the rates from your Excel file?')){localStorage.setItem(PAY_SETTINGS_KEY,JSON.stringify(PAY_DEFAULTS));fillPaySettings();renderPayroll()}});
document.addEventListener('click',e=>{let b=e.target.closest('[data-delete-flight]');if(b){save(FLIGHTS_KEY,load(FLIGHTS_KEY).filter(f=>f.id!==b.dataset.deleteFlight));render();return}b=e.target.closest('[data-edit-flight]');if(b){const f=load(FLIGHTS_KEY).find(x=>x.id===b.dataset.editFlight);if(!f)return;$('editId').value=f.id;['dutyTypeFlight','date','flightNo','reg','type','dep','arr','schedOut','schedIn','out','off','on','in','role','instructionType','landings','night','ifr','remarks'].forEach(id=>{const key={dutyTypeFlight:'dutyType'}[id]||id;if($(id))$(id).value=f[key]??''});$('entryTitle').textContent='Edit log entry';$('saveEntryBtn').textContent='Update entry';calcEntry();show('addView');return}b=e.target.closest('[data-delete-duty]');if(b){save(DUTY_KEY,load(DUTY_KEY).filter(d=>d.id!==b.dataset.deleteDuty));render();return}b=e.target.closest('[data-delete-trip]');if(b){save(TRIPS_KEY,load(TRIPS_KEY).filter(t=>t.id!==b.dataset.deleteTrip));renderTrips();return}b=e.target.closest('[data-roster-action]');if(b){const rs=load(ROSTER_KEY),r=rs.find(x=>x.id===b.dataset.rosterAction);if(!r)return;if(r.status==='done'){r.status='planned';save(ROSTER_KEY,rs);render();return}const existing=load(FLIGHTS_KEY).find(f=>f.date===r.date&&String(f.flightNo||'').toUpperCase()===String(r.flightNo||'').toUpperCase()&&f.dep===r.dep&&f.arr===r.arr);if(existing){const edit=document.querySelector(`[data-edit-flight="${existing.id}"]`);if(edit)edit.click();else{const f=existing;$('editId').value=f.id;$('date').value=f.date;$('flightNo').value=f.flightNo;$('dep').value=f.dep;$('arr').value=f.arr;$('schedOut').value=f.schedOut||r.std||'';$('schedIn').value=f.schedIn||r.sta||'';show('addView')}}else{resetEntry();$('date').value=r.date||'';$('flightNo').value=r.flightNo||'';$('dep').value=r.dep||'';$('arr').value=r.arr||'';$('type').value=r.type||'';$('reg').value=r.reg||'';$('schedOut').value=r.std||'';$('schedIn').value=r.sta||'';$('remarks').value='Imported from roster'}r.status='done';save(ROSTER_KEY,rs);render();show('addView')}});
resetEntry();resetTrip();$('dutyDate').value=today();$('payrollMonth').value=monthNow();fillPaySettings();render();show('dashboardView');console.log('PilotLog v'+VERSION+' loaded');
});
})();
