
const FLIGHTS_KEY='pilotlog_flights_v1', ROSTER_KEY='pilotlog_roster_v2', DUTY_KEY='pilotlog_duties_v2';
const makeId=()=>{try{if(globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function')return globalThis.crypto.randomUUID()}catch(e){}return 'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10)};
const todayLocal=()=>{const d=new Date(), y=d.getFullYear(), m=String(d.getMonth()+1).padStart(2,'0'), day=String(d.getDate()).padStart(2,'0'); return `${y}-${m}-${day}`};
const $=id=>document.getElementById(id); const loadKey=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}}; const saveKey=(k,d)=>localStorage.setItem(k,JSON.stringify(d));
const mins=t=>{if(!t)return null;const[a,b]=String(t).split(':').map(Number);return a*60+b}; const diff=(a,b)=>{if(a==null||b==null)return 0;let d=b-a;if(d<0)d+=1440;return d}; const fmt=m=>`${Math.floor((m||0)/60)}:${String((m||0)%60).padStart(2,'0')}`; const creditMins=m=>m>0?Math.ceil(m/30)*30:0;
const escHtml=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function calc(){const block=diff(mins($('out').value),mins($('in').value)),flt=diff(mins($('off').value),mins($('on').value)),credit=creditMins(block);$('blockDisplay').value=fmt(block);$('creditDisplay').value=fmt(credit);$('calcPreview').textContent=`Block ${fmt(block)} • Flight ${fmt(flt)} • Credit ${fmt(credit)}`;return{block,flt,credit}}
['out','off','on','in'].forEach(x=>$(x).addEventListener('input',calc));
function startOfDaysAgo(n){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-n+1);return d}
function rolling(data,n){const cut=startOfDaysAgo(n);return data.reduce((s,f)=>s+(new Date(f.date+'T00:00:00')>=cut?(Number(f.block)||0):0),0)}
function render(){const raw=loadKey(FLIGHTS_KEY);let changed=false;raw.forEach(f=>{if(f.credit==null){f.credit=creditMins(Number(f.block)||0);changed=true}if(!f.dutyType){f.dutyType=f.sim==='yes'?'Simulator':'Flight';changed=true}});if(changed)saveKey(FLIGHTS_KEY,raw);const data=raw.sort((a,b)=>b.date.localeCompare(a.date));let tb=0,tp=0,ti=0;data.forEach(f=>{tb+=Number(f.block)||0;if(f.role==='PIC')tp+=Number(f.block)||0;if(f.role==='Instructor'||f.instructionType)ti+=Number(f.block)||0});$('mBlock').textContent=fmt(tb);$('mPic').textContent=fmt(tp);$('mTri').textContent=fmt(ti);$('mFlights').textContent=data.length;$('p28').textContent=fmt(rolling(data,28));$('p90').textContent=fmt(rolling(data,90));$('p365').textContent=fmt(rolling(data,365));$('recentFlights').innerHTML=flightHtml(data.slice(0,5));$('allFlights').innerHTML=flightHtml(data,true);renderRoster();renderDuties()}
function flightHtml(data,full=false){if(!data.length)return '<div class="empty">No flights yet.</div>';return data.map(f=>`<div class="flight"><div><div class="route">${escHtml(f.dep)} → ${escHtml(f.arr)}</div><div class="small">${escHtml(f.date)} ${escHtml(f.flightNo||'')}</div><span class="pill">${escHtml(f.dutyType||'Flight')}</span><span class="pill">${escHtml(f.type||'Aircraft')}</span><span class="pill">${escHtml(f.role||'')}</span>${f.instructionType?`<span class="pill green">${escHtml(f.instructionType)}</span>`:''}${f.sim==='yes'?'<span class="pill orange">SIM</span>':''}</div><div class="meta"><b>${fmt(f.block)}</b> block<br><span class="small">${fmt(f.credit??creditMins(Number(f.block)||0))} credit • ${fmt(f.flight)} flight • ${escHtml(f.reg||'')}</span></div>${full?`<button class="danger" onclick="removeFlight('${f.id}')">Delete</button>`:''}</div>`).join('')}
window.removeFlight=id=>{saveKey(FLIGHTS_KEY,loadKey(FLIGHTS_KEY).filter(f=>f.id!==id));render()};
$('flightForm').addEventListener('submit',e=>{e.preventDefault();try{const c=calc();const dutyType=$('dutyTypeFlight').value;if(!$('date').value){alert('Please enter the date.');return}if((dutyType==='Flight'||dutyType==='DHD')&&(!$('dep').value.trim()||!$('arr').value.trim())){alert('Please enter From and To.');return}const f={id:makeId(),dutyType,date:$('date').value,flightNo:$('flightNo').value.trim().toUpperCase(),dep:$('dep').value.trim().toUpperCase(),arr:$('arr').value.trim().toUpperCase(),type:$('type').value.trim().toUpperCase(),reg:$('reg').value.trim().toUpperCase(),schedOut:$('schedOut').value,schedIn:$('schedIn').value,out:$('out').value,off:$('off').value,on:$('on').value,in:$('in').value,block:c.block,flight:c.flt,credit:c.credit,role:$('role').value,instructionType:$('instructionType').value,landings:Number($('landings').value||0),night:$('night').value,sim:dutyType==='Simulator'?'yes':'no',ifr:$('ifr').value,remarks:$('remarks').value.trim()};const data=loadKey(FLIGHTS_KEY);data.push(f);saveKey(FLIGHTS_KEY,data);resetFlightForm();render();show('dashboardView');alert('Entry saved successfully.')}catch(err){console.error(err);alert('Unable to save entry: '+(err&&err.message?err.message:String(err)))}});
$('clearForm').onclick=resetFlightForm;
$('deleteAll').onclick=()=>{if(confirm('Delete all saved flights?')){localStorage.removeItem(FLIGHTS_KEY);render()}};
const csvEsc=v=>'"'+String(v??'').replaceAll('"','""')+'"';
$('exportCsv').onclick=()=>{const d=loadKey(FLIGHTS_KEY);if(!d.length)return alert('No flights to export');const cols=['dutyType','date','flightNo','reg','type','dep','arr','schedOut','schedIn','out','off','on','in','block','credit','flight','role','instructionType','landings','night','sim','ifr','remarks'];downloadCsv('pilotlog_logbook.csv',[cols.join(','),...d.map(r=>cols.map(c=>csvEsc(r[c])).join(','))].join('\n'))};
function downloadCsv(name,csv){const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"'){q=!q}else if(c===','&&!q){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());cell='';if(row.some(x=>x!==''))rows.push(row);row=[]}else cell+=c}row.push(cell.trim());if(row.some(x=>x!==''))rows.push(row);return rows}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
const aliases={date:['date','day'],flightNo:['flightno','flightnumber','flight','flt'],dep:['dep','departure','from','origin'],arr:['arr','arrival','to','destination'],report:['report','reporting','reporttime'],std:['std','departuretime','scheduleddeparture','offblock'],sta:['sta','arrivaltime','scheduledarrival','onblock'],endDuty:['endduty','dutyend','end','released'],type:['type','aircrafttype','acfttype'],reg:['reg','registration','aircraftregistration']};
function fieldFor(h){const x=norm(h);return Object.keys(aliases).find(k=>aliases[k].includes(x))||null}
function normalDate(v){v=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;let m=v.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})$/);if(m){let y=m[3].length===2?'20'+m[3]:m[3];return `${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}return v}
$('rosterFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const rows=parseCsv(await file.text());if(rows.length<2)return alert('CSV contains no data');const map=rows[0].map(fieldFor), imported=rows.slice(1).map(r=>{const o={id:makeId(),status:'planned'};map.forEach((k,i)=>{if(k)o[k]=r[i]||''});o.date=normalDate(o.date);o.dep=(o.dep||'').toUpperCase();o.arr=(o.arr||'').toUpperCase();o.flightNo=(o.flightNo||'').toUpperCase();o.type=(o.type||'').toUpperCase();o.reg=(o.reg||'').toUpperCase();return o}).filter(x=>x.date&&(x.dep||x.arr||x.flightNo));const existing=loadKey(ROSTER_KEY);saveKey(ROSTER_KEY,[...existing,...imported]);e.target.value='';render();alert(`${imported.length} roster sectors imported`)});
function renderRoster(){const all=loadKey(ROSTER_KEY).sort((a,b)=>(a.date+a.std).localeCompare(b.date+b.std));const today=todayLocal(),up=all.filter(r=>r.date>=today).slice(0,6);$('upcomingRoster').innerHTML=rosterHtml(up,false);$('rosterList').innerHTML=rosterHtml(all,true)}
function rosterHtml(data,actions){if(!data.length)return '<div class="empty">No roster imported.</div>';return data.map(r=>`<div class="roster-row"><div><b>${escHtml(r.date)}</b><div class="small">${escHtml(r.report?`RPT ${r.report}`:'')}</div></div><div><b>${escHtml(r.flightNo||'Duty')}</b> ${escHtml(r.dep||'')} → ${escHtml(r.arr||'')}<div class="small">${escHtml(r.std||'')} ${r.sta?'– '+escHtml(r.sta):''} ${r.endDuty?'• END '+escHtml(r.endDuty):''}</div></div><div class="extra"><span class="pill">${escHtml(r.type||'Roster')}</span><span class="status ${r.status==='done'?'done':'planned'}">${r.status==='done'?'Logged':'Planned'}</span></div>${actions?`<button class="${r.status==='done'?'secondary':'primary'}" onclick="rosterAction('${r.id}')">${r.status==='done'?'Undo':'Log'}</button>`:'<div></div>'}</div>`).join('')}
window.rosterAction=id=>{const roster=loadKey(ROSTER_KEY),r=roster.find(x=>x.id===id);if(!r)return;if(r.status==='done'){r.status='planned';saveKey(ROSTER_KEY,roster);return render()}$('date').value=r.date||'';$('flightNo').value=r.flightNo||'';$('dep').value=r.dep||'';$('arr').value=r.arr||'';$('type').value=r.type||'';$('reg').value=r.reg||'';$('schedOut').value=r.std||'';$('schedIn').value=r.sta||'';$('out').value=r.std||'';$('off').value='';$('on').value='';$('in').value=r.sta||'';$('remarks').value='Imported from roster';calc();r.status='done';saveKey(ROSTER_KEY,roster);show('addView');render()};
$('clearRoster').onclick=()=>{if(confirm('Clear imported roster?')){localStorage.removeItem(ROSTER_KEY);render()}};
$('exportRoster').onclick=()=>{const d=loadKey(ROSTER_KEY);if(!d.length)return alert('No roster to export');const cols=['date','flightNo','dep','arr','report','std','sta','endDuty','type','reg','status'];downloadCsv('pilotlog_roster.csv',[cols.join(','),...d.map(r=>cols.map(c=>csvEsc(r[c])).join(','))].join('\n'))};
$('dutyForm').addEventListener('submit',e=>{e.preventDefault();const d=loadKey(DUTY_KEY);d.push({id:makeId(),date:$('dutyDate').value,type:$('dutyType').value,report:$('reportTime').value,end:$('endDuty').value,minutes:diff(mins($('reportTime').value),mins($('endDuty').value)),notes:$('dutyNotes').value.trim()});saveKey(DUTY_KEY,d);e.target.reset();$('dutyDate').value=todayLocal();render()});
function renderDuties(){const d=loadKey(DUTY_KEY).sort((a,b)=>b.date.localeCompare(a.date));$('dutyList').innerHTML=!d.length?'<div class="empty">No duties yet.</div>':d.map(x=>`<div class="duty"><div><b>${escHtml(x.type)}</b><div class="small">${escHtml(x.date)} • ${escHtml(x.notes||'')}</div></div><div class="meta"><b>${fmt(x.minutes)}</b><div class="small">${escHtml(x.report||'')} ${x.end?'– '+escHtml(x.end):''}</div></div><button class="danger" onclick="removeDuty('${x.id}')">Delete</button></div>`).join('')}
window.removeDuty=id=>{saveKey(DUTY_KEY,loadKey(DUTY_KEY).filter(x=>x.id!==id));render()};
function show(id){document.querySelectorAll('main section').forEach(s=>s.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id))} document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
$('date').value=todayLocal();$('dutyDate').value=todayLocal();render();calc();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
